server:
  port: 9019

grpc:
  port: 8000

spring:
  application:
    name: analyze-service

  kafka:
    producer:
      bootstrap-servers: localhost:9092

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/data_analyze
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml